spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bookstroe?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

